### ISSUE TITLE
Implement --version option

### ISSUE THREAD

**Issue by forwardpointer** [microsoft/wifi-ztp#18]
**Is your feature request related to a problem? Please describe.**
.

**Describe the solution you'd like**
I would like ztpd --version to output the version that the ztpd binary is. To my knowledge there is no other way to check the version of the binary. Having this information outputted in the logs would also help debugging.

**Describe alternatives you've considered**
.

**Additional context**
.

**Comment by abeltrano** [comment]
Please ensure the version is defined using [semver](https://semver.org/) format.

**Comment by forwardpointer** [comment]
A current workaround for this is to query the package manager:
```
rpm -qa | grep ztpd
```

**Comment by abeltrano** [comment]
> A current workaround for this is to query the package manager:
> 
> ```
> rpm -qa | grep ztpd
> ```

This works ok for rpm-based distros, but won't work for .deb-based distros (Debian, Ubuntu). For the former, consider using [rpm query tags](https://rpm.org/user_doc/query_format.html#:~:text=RPM%20Query%20Formats%201%20Tags.%20All%20of%20the,4%20Formatting%20Tags.%20...%205%20Query%20Expressions.%20) to extract very specific versioning information. Be careful as well, since if multiple versions are installed, you need to take care to format/filter/select the expected output. It's not trivial to list the "latest"/"newest" version installed.
